import { TFunction } from 'i18next';
import i18n from '@/lib/i18n';

// Register statTitles bundle for en/ar at runtime (non-destructive)
const enStatTitles = {
  tabs: {
    overview: 'Overview',
    leads: 'Recent Leads',
    campaigns: 'Campaigns',
    analytics: 'Analytics'
  },
  actions: {
    exportReport: 'Export Report',
    newCampaign: 'New Campaign',
    addNewLead: 'Add New Lead',
    createCampaign: 'Create Campaign',
    exportData: 'Export Data',
    viewReports: 'View Reports',
    filter: 'Filter',
    search: 'Search'
  },
  sample: {
    noticeTitle: 'Sample Dashboard Notice',
    noticeBody: 'This is a sample dashboard showing how your workflow dashboard will look when you purchase this workflow. All data shown is for demonstration purposes only.'
  },
  pages: {
    lead: {
      title: 'Lead Generation Dashboard',
      subtitle: 'Automated lead generation and qualification system'
    },
    websiteChatbot: {
      title: 'Website Chatbot Dashboard',
      subtitle: 'Monitor and manage your AI-powered website chatbot interactions'
    },
    localChatbot: {
      title: 'Local RAG Chatbot Dashboard',
      subtitle: 'AI-powered local document search and conversation system'
    }
  },
  statTitles: {
    totalSessions: 'Total Sessions',
    activeSessions: 'Active Sessions',
    resolvedQueries: 'Resolved Queries',
    avgResponseTime: 'Avg Response Time',
    accuracyRate: 'Accuracy Rate',
    satisfactionRate: 'Satisfaction Rate',
    totalConversations: 'Total Conversations',
    activeUsers: 'Active Users',
    responseTime: 'Response Time',
    questionsAnswered: 'Questions Answered',
    knowledgeBaseQueries: 'Knowledge Base Queries',
    databaseQueries: 'Database Queries',
    aiConversations: 'AI Conversations',
    successfulQueries: 'Successful Queries',
    failedQueries: 'Failed Queries',
    avgQueryTime: 'Avg Query Time',
    memorySessions: 'Memory Sessions',
    uniqueUsers: 'Unique Users'
  },
  statLabels: {
    avgResponseHint: 'Average response time'
  },
  buttons: {
    startAutomationLabel: 'Start Automation',
    pauseAutomationLabel: 'Pause Automation',
    refresh: 'Refresh',
    requestStart: 'Request Start',
    requestStop: 'Request Stop',
    requestChanges: 'Request Changes',
    pauseBot: 'Pause Bot',
    join: 'Join',
    startAutoResponse: 'Start Auto-Response',
    updateKnowledgeBase: 'Update Knowledge Base',
    trainAiModel: 'Train AI Model'
  },
  sections: {
    workflowControl: 'Workflow Control',
    pendingRequests: 'Pending Requests',
    recentProcessedRequests: 'Recent Processed Requests',
    automationStatus: 'Automation Status',
    recentChatSessions: 'Recent Chat Sessions',
    sessionStatusPipeline: 'Session Status Pipeline',
    popularTopics: 'Popular Topics',
    conversationFlow: 'Conversation Flow',
    quickActions: 'Quick Actions',
    systemHealth: 'System Health',
    localAiControls: 'Local AI Controls',
    chatbotControls: 'Chatbot Controls'
  },
  labels: {
    workflowControlDesc: 'Request admin to start, stop, or modify your workflow',
    requestsAwaitingApproval: 'Your workflow control requests awaiting admin approval',
    recentlyApprovedOrRejected: 'Your recently approved or rejected workflow requests',
    on: 'on',
    source: 'Source',
    start: 'Start',
    stop: 'Stop',
    changes: 'Changes',
    startDesc: 'Request admin to activate your workflow',
    stopDesc: 'Request admin to pause your workflow',
    changesDesc: 'Request modifications to workflow settings',

    performanceOverview: 'Performance Overview',
    quickActions: 'Quick Actions',
    recentLeads: 'Recent Leads',
    activeCampaigns: 'Active Campaigns',
    leadSources: 'Lead Sources',
    responseTimeAnalysis: 'Response Time Analysis',

    performanceOverTime: 'Lead generation performance over time',
    commonTasks: 'Common tasks and shortcuts',
    latestLeads: 'Latest leads generated by the system',
    currentCampaigns: 'Current lead generation campaigns and their performance',
    leadSourceDistribution: 'Distribution of leads by source',
    averageResponseByStatus: 'Average response times by lead status',

    leadGenerationProgress: 'Lead Generation Progress',
    targetLeads: 'Target: {{count}} leads',
    generated: 'generated',
    successRate: 'Success Rate',

    websiteIntegration: 'Website Integration',
    aiChatEngine: 'AI Chat Engine',
    messageQueue: 'Message Queue',
    healthy: 'Healthy',
    online: 'Online',

    databaseQueriesToday: 'Database Queries Today',
    averageQueryTime: 'Average Query Time',
    queryComplexity: 'Query Complexity',
    ragQueriesToday: 'RAG queries today',
    lastUpdated: 'Last updated:',
    submittedOn: 'Submitted',
    liveDashboard: 'Live Dashboard',
    live: 'Live',
    vectorDatabase: 'Vector Database',
    connected: 'Connected',
    documentIndex: 'Document Index',
    docs: 'docs',

    distributionByStatus: 'Distribution of chat sessions by status',
    commonTopicsDesc: 'Most common conversation topics',
    latestVisitorInteractions: 'Latest visitor interactions with your chatbot',
    currentlyOngoingChats: 'Currently ongoing chat conversations',
    manageWebsiteChatbotAutomation: 'Manage your website chatbot automation',
    activeForMinutes: 'Active for {{minutes}}m',
    messages: 'messages',
    systemHealthDesc: 'Monitor chatbot system components'
  },
  topics: {
    productInformation: 'Product Information',
    pricing: 'Pricing',
    technicalSupport: 'Technical Support',
    generalInquiry: 'General Inquiry',
    orderStatus: 'Order Status'
  },
  badgeStatus: {
    approved: 'Approved',
    rejected: 'Rejected',
    active: 'Active',
    resolved: 'Resolved',
    escalated: 'Escalated',
    abandoned: 'Abandoned',
    pending: 'Pending',
    paused: 'Paused',
    live: 'Live'
  }
};

const arStatTitles = {
  tabs: {
    overview: 'نظرة عامة',
    leads: 'أحدث العملاء',
    campaigns: 'الحملات',
    analytics: 'التحليلات'
  },
  actions: {
    exportReport: 'تصدير التقرير',
    newCampaign: 'حملة جديدة',
    addNewLead: 'إضافة عميل جديد',
    createCampaign: 'إنشاء حملة',
    exportData: 'تصدير البيانات',
    viewReports: 'عرض التقارير',
    filter: 'تصفية',
    search: 'بحث'
  },
  sample: {
    noticeTitle: 'تنبيه لوحة تجريبية',
    noticeBody: 'هذه لوحة تجريبية توضح لك كيف ستبدو لوحة معلومات سير العمل عند شراء هذا السير. جميع البيانات المعروضة لأغراض العرض فقط.'
  },
  pages: {
    lead: {
      title: 'لوحة توليد العملاء',
      subtitle: 'نظام آلي لتوليد العملاء وتأهيلهم'
    },
    websiteChatbot: {
      title: 'لوحة روبوت الدردشة للموقع',
      subtitle: 'راقب وأدر محادثات روبوت الدردشة في موقعك المدعوم بالذكاء الاصطناعي'
    },
    localChatbot: {
      title: 'لوحة روبوت الدردشة المحلي (RAG)',
      subtitle: 'نظام بحث ومحادثة على مستنداتك المحلية بالذكاء الاصطناعي'
    }
  },
  statTitles: {
    totalSessions: 'إجمالي الجلسات',
    activeSessions: 'الجلسات النشطة',
    resolvedQueries: 'الاستفسارات المحلولة',
    avgResponseTime: 'متوسط زمن الاستجابة',
    accuracyRate: 'معدل الدقة',
    satisfactionRate: 'معدل الرضا',
    totalConversations: 'إجمالي المحادثات',
    activeUsers: 'المستخدمون النشطون',
    responseTime: 'زمن الاستجابة',
    questionsAnswered: 'الأسئلة المُجاب عنها',
    knowledgeBaseQueries: 'استعلامات قاعدة المعرفة',
    databaseQueries: 'استعلامات قاعدة البيانات',
    aiConversations: 'محادثات الذكاء الاصطناعي',
    successfulQueries: 'الاستعلامات الناجحة',
    failedQueries: 'الاستعلامات الفاشلة',
    avgQueryTime: 'متوسط زمن الاستعلام',
    memorySessions: 'جلسات الذاكرة',
    uniqueUsers: 'المستخدمون الفريدون'
  },
  statLabels: {
    avgResponseHint: 'متوسط زمن الاستجابة'
  },
  buttons: {
    startAutomationLabel: 'بدء التشغيل الآلي',
    pauseAutomationLabel: 'إيقاف مؤقت للتشغيل الآلي',
    refresh: 'تحديث',
    requestStart: 'طلب البدء',
    requestStop: 'طلب الإيقاف',
    requestChanges: 'طلب تغييرات',
    pauseBot: 'إيقاف الروبوت',
    join: 'انضمام',
    startAutoResponse: 'بدء الرد الآلي',
    updateKnowledgeBase: 'تحديث قاعدة المعرفة',
    trainAiModel: 'تدريب نموذج الذكاء الاصطناعي'
  },
  sections: {
    workflowControl: 'التحكم بالسير الآلي',
    pendingRequests: 'الطلبات المعلقة',
    recentProcessedRequests: 'أحدث الطلبات المعالجة',
    automationStatus: 'حالة التشغيل الآلي',
    recentChatSessions: 'آخر جلسات الدردشة',
    sessionStatusPipeline: 'خط حالة الجلسة',
    popularTopics: 'المواضيع الشائعة',
    conversationFlow: 'تدفق المحادثة',
    quickActions: 'إجراءات سريعة',
    systemHealth: 'صحة النظام',
    localAiControls: 'ضبط الذكاء المحلي',
    chatbotControls: 'ضبط روبوت الدردشة'
  },
  labels: {
    workflowControlDesc: 'اطلب من المشرف بدء أو إيقاف أو تعديل سير العمل الخاص بك',
    requestsAwaitingApproval: 'طلبات التحكم في سير العمل بانتظار موافقة المشرف',
    recentlyApprovedOrRejected: 'أحدث الطلبات التي تم قبولها أو رفضها',
    on: 'في',
    source: 'المصدر',
    start: 'بدء',
    stop: 'إيقاف',
    changes: 'تغييرات',
    startDesc: 'طلب تفعيل سير العمل',
    stopDesc: 'طلب إيقاف سير العمل مؤقتًا',
    changesDesc: 'طلب تعديلات على إعدادات سير العمل',

    performanceOverview: 'نظرة عامة على الأداء',
    quickActions: 'إجراءات سريعة',
    recentLeads: 'أحدث العملاء',
    activeCampaigns: 'الحملات النشطة',
    leadSources: 'مصادر العملاء',
    responseTimeAnalysis: 'تحليل أزمنة الاستجابة',

    performanceOverTime: 'أداء توليد العملاء مع مرور الوقت',
    commonTasks: 'مهام شائعة واختصارات',
    latestLeads: 'أحدث العملاء الذين تم توليدهم بواسطة النظام',
    currentCampaigns: 'الحملات الحالية وأداؤها',
    leadSourceDistribution: 'توزيع العملاء حسب المصدر',
    averageResponseByStatus: 'متوسط أزمنة الاستجابة حسب الحالة',

    leadGenerationProgress: 'تقدم توليد العملاء',
    targetLeads: 'الهدف: {{count}} عميل',
    generated: 'تم توليدها',
    successRate: 'معدل النجاح',

    websiteIntegration: 'تكامل الموقع',
    aiChatEngine: 'محرك دردشة الذكاء الاصطناعي',
    messageQueue: 'قائمة الرسائل',
    healthy: 'سليم',
    online: 'متصل',

    databaseQueriesToday: 'استعلامات اليوم في قاعدة البيانات',
    averageQueryTime: 'متوسط زمن الاستعلام',
    queryComplexity: 'تعقيد الاستعلام',
    ragQueriesToday: 'استعلامات RAG اليوم',
    lastUpdated: 'آخر تحديث:',
    submittedOn: 'تم الإرسال',
    liveDashboard: 'لوحة تحكم حية',
    live: 'مباشر',
    vectorDatabase: 'قاعدة بيانات متجهة',
    connected: 'متصل',
    documentIndex: 'فهرس الوثائق',
    docs: 'وثائق',

    distributionByStatus: 'توزيع جلسات الدردشة حسب الحالة',
    commonTopicsDesc: 'أكثر مواضيع المحادثة شيوعاً',
    latestVisitorInteractions: 'آخر تفاعلات الزوار مع روبوت الدردشة',
    currentlyOngoingChats: 'المحادثات الجارية حالياً',
    manageWebsiteChatbotAutomation: 'إدارة أتمتة روبوت الدردشة للموقع',
    activeForMinutes: 'نشط منذ {{minutes}} د',
    messages: 'رسائل',
    systemHealthDesc: 'مراقبة مكونات نظام روبوت الدردشة'
  },
  topics: {
    productInformation: 'معلومات المنتج',
    pricing: 'الأسعار',
    technicalSupport: 'الدعم الفني',
    generalInquiry: 'استفسار عام',
    orderStatus: 'حالة الطلب'
  },
  badgeStatus: {
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    active: 'نشط',
    resolved: 'محلول',
    escalated: 'مُصعَّد',
    abandoned: 'مهجور',
    pending: 'معلق',
    paused: 'متوقف مؤقتاً',
    live: 'مباشر'
  }
};

try {
  if (!i18n.hasResourceBundle('en', 'translation')) {
    // i18n will initialize it elsewhere; ignore here
  }
  i18n.addResourceBundle('en', 'translation', enStatTitles, true, true);
  i18n.addResourceBundle('ar', 'translation', arStatTitles, true, true);
} catch (e) {
  // non-fatal in case i18n not ready yet
}

// Map common English stat titles to translation keys under statTitles.*
const STAT_TITLE_KEY: Record<string, string> = {
  'Total Sessions': 'totalSessions',
  'Active Sessions': 'activeSessions',
  'Resolved Queries': 'resolvedQueries',
  'Avg Response Time': 'avgResponseTime',
  'Accuracy Rate': 'accuracyRate',
  'Satisfaction Rate': 'satisfactionRate',
  'Total Conversations': 'totalConversations',
  'Active Users': 'activeUsers',
  'Response Time': 'responseTime',
  'Questions Answered': 'questionsAnswered',
  'Knowledge Base Queries': 'knowledgeBaseQueries',
  'Database Queries': 'databaseQueries',
  'AI Conversations': 'aiConversations',
  'Successful Queries': 'successfulQueries',
  'Failed Queries': 'failedQueries',
  'Avg Query Time': 'avgQueryTime',
  'Memory Sessions': 'memorySessions',
  'Unique Users': 'uniqueUsers'
};

export function tStatTitle(title: string, t: TFunction<'translation'>): string {
  if (!title) return title;
  const key = STAT_TITLE_KEY[title.trim()];
  if (key) return t(`statTitles.${key}`, title);
  return t(title, title);
}

